name       : pytest-runner
version    : '5.1'
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/p/pytest-runner/pytest-runner-5.1.tar.gz : 25a013c8d84f0ca60bb01bd11913a3bcab420f601f0f236de4423074af656e7a
license    : MIT
component  : programming.python
summary    : Test support for python setup.py projects
description: |
    Setup scripts can use pytest-runner to add setup.py test support for pytest runner.
builddeps  :
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - python-pytest
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
