name       : pytest-runner
version    : 4.2
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/p/pytest-runner/pytest-runner-4.2.tar.gz : d23f117be39919f00dd91bffeb4f15e031ec797501b717a245e377aee0f577be
license    : MIT
component  : programming.python
summary    : Test support for python setup.py projects
description: |
    Setup scripts can use pytest-runner to add setup.py test support for pytest runner.
builddeps  :
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - python-pytest
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
