name       : pytest-runner
version    : 2.11.1
release    : 2
source     :
    - https://pypi.python.org/packages/9e/4d/08889e5e27a9f5d6096b9ad257f4dea1faabb03c5ded8f665ead448f5d8a/pytest-runner-2.11.1.tar.gz : 983a31eab45e375240e250161a556163bc8d250edaba97960909338c273a89b3
license    : MIT
component  : programming.python
summary    : Test support for python setup.py projects
description: |
    Test support for python setup.py projects
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
    - setuptools_scm
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install