name       : pytest-runner
version    : '3.0'
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/p/pytest-runner/pytest-runner-3.0.tar.gz : 0f7c3a3cf5aead13f54baaa01ceb49e5ae92aba5d3ff1928e81e189c40bc6703
license    : MIT
component  : programming.python
summary    : Test support for python setup.py projects
description: |
    Setup scripts can use pytest-runner to add setup.py test support for pytest runner.
builddeps  :
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - python-pytest
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
