name       : pytest-runner
version    : '5.2'
release    : 11
source     :
    - https://files.pythonhosted.org/packages/source/p/pytest-runner/pytest-runner-5.2.tar.gz : 96c7e73ead7b93e388c5d614770d2bae6526efd997757d3543fe17b557a0942b
license    : MIT
component  : programming.python
summary    : Test support for python setup.py projects
description: |
    Setup scripts can use pytest-runner to add setup.py test support for pytest runner.
builddeps  :
    - python2-pytest
    - python-pytest # check
    - python-pytest-cov # check
    - python-pytest-flake8 # check
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - python-pytest
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    #python_test pytest
    #python3_test pytest3 # needs pytest-black packaged
